# TPESOUT: verify this is right
# RNA-seq CGL Pipeline configuration file
# This configuration file is formatted in YAML. Simply write the value (at least one space) after the colon.
# Edit the values in this configuration file and then rerun the pipeline: "toil-rnaseq-sc run"
# Just Kallisto or STAR/RSEM can be run by supplying only the inputs to those tools
#
# URLs can take the form: http://, ftp://, file://, s3://, gnos://
# Local inputs follow the URL convention: file:///full/path/to/input
# S3 URLs follow the convention: s3://bucket/directory/file.txt
#
# Comments (beginning with #) do not need to be removed. Optional parameters left blank are treated as false.
##############################################################################################################
# Required: URL ['http://', 'file://', 's3://', 'ftp://', 'gnos://'] to kallisto index file.
kallisto-index: file:///home/trevorp/genomic/cgl/testing_data/in/transcripts.idx

# Required: Output location of sample. Can be full path to a directory or an s3:// URL
# Warning: S3 buckets must exist prior to upload or it will fail.
output-dir: file:///home/trevorp/genomic/cgl/testing_data/out/

# Optional: Provide a full path to a 32-byte key used for SSE-C Encryption in Amazon
ssec:

# Optional: If true, uses resource requirements appropriate for continuous integration
ci-test: true
